version: "1.28.2"
services: 
  db: 
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fibonacci
    volume:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - '5432:5432'
  web:
    image: 
    depends_on:
      -db
    ports: 
     -'4000:4000'
