version: "3"
services: 
  postgres: 
    image: postgres
    container_name: postgres-fibonacci
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fibonacci
      POSTGRES_HOST_AUTH_METHOD: trust 
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - '5430:5432'
  web:
    build: .
    image: node-docker
    environment: 
      DB_HOST: postgres
      DB_NAME: fibonacci
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5430
    depends_on:
      - postgres
    ports: 
     - '4000:3000'
